Repository gaemi-marble/gaemi-marble, pull requests merged in 2023-11, with the labels that each got.

#4 [FE] 게임종료 기능 구현
  .github/workflows/deploy.yml
  fe/package-lock.json
  fe/package.json
  fe/src/components/GameBoard/Cell.tsx
  fe/src/components/GameBoard/CenterArea.tsx
  fe/src/components/GameBoard/Dice.tsx
  fe/src/components/GameBoard/Roulette.tsx
  fe/src/components/Modal/GameOverModal/GameOverModal.tsx
  fe/src/components/Modal/GameOverModal/GameOverModalContent.tsx
  fe/src/components/Modal/GameOverModal/PlayerRank.tsx
  fe/src/components/Player/PlayerCard.tsx
  fe/src/hooks/useMoveToken.ts
  fe/src/hooks/useWindowSize.ts
  fe/src/pages/GamePage.tsx
  fe/src/store/reducer/constants.ts
  fe/src/store/reducer/type.ts
  fe/src/store/reducer/useGameReducer.ts
Labels: fe, feat

#3 [FE] 재 접속 및 예외 발생 기능
  fe/src/components/GameBoard/Roulette.tsx
  fe/src/components/GameBoard/constants.ts
  fe/src/components/Modal/EnterModal/EnterModalContent.tsx
  fe/src/hooks/useMoveToken.ts
  fe/src/pages/GamePage.tsx
  fe/src/store/reducer/type.ts
  fe/src/store/reducer/useGameReducer.tsx
Labels: fe, feat

#10 [FE] 바뀐 룰렛 방식에 맞게 코드 리팩터링
  fe/src/components/GameBoard/Roulette.tsx
  fe/src/store/reducer/constants.ts
  fe/src/store/reducer/index.ts
  fe/src/store/reducer/type.ts
  fe/src/store/reducer/useGameReducer.tsx
Labels: fe, refactor

#15 refactor: 프로젝트 전반적인 리팩토링
  fe/package-lock.json
  fe/package.json
  fe/src/api/index.ts
  fe/src/components/GameBoard/CenterArea.tsx
  fe/src/components/GameBoard/Dice.tsx
  fe/src/components/GameBoard/GameBoard.tsx
  fe/src/components/GameBoard/PlayerToken.tsx
  fe/src/components/GameBoard/Roulette.tsx
  fe/src/components/GameBoard/constants.ts
  fe/src/components/Header/GameHeader.tsx
  fe/src/components/Header/HomeHeader.tsx
  fe/src/components/Modal/EnterModal/EnterModalContent.tsx
  fe/src/components/Modal/EventModal/EventModal.tsx
  fe/src/components/Modal/EventModal/EventModalContent.tsx
  fe/src/components/Modal/GameOverModal/GameOverModal.tsx
  fe/src/components/Modal/GameOverModal/GameOverModalContent.tsx
  fe/src/components/Modal/GameOverModal/PlayerRank.tsx
  fe/src/components/Modal/StatusBoardModal/StatusBoardModalContent.tsx
  fe/src/components/Modal/StockBuyModal/StockBuyModalContent.tsx
  fe/src/components/Modal/StockSellModal/StockSellTableData.tsx
  fe/src/components/Player/PlayerCard.tsx
  fe/src/components/Player/PlayerInfo.tsx
  fe/src/components/Player/PlayerStockTooltip.tsx
  fe/src/components/constants.ts
  fe/src/hooks/useMoveToken.ts
  fe/src/main.tsx
  fe/src/mocks/browser.ts
  fe/src/mocks/handlers.ts
  fe/src/pages/GamePage.tsx
  fe/src/pages/HomePage.tsx
  fe/src/pages/SignInPage.tsx
  fe/src/pages/SignUpPage.tsx
  fe/src/pages/constants.ts
  fe/src/router/constants.ts
  fe/src/router/router.tsx
  fe/src/store/reducer/constants.ts
  fe/src/store/reducer/index.ts
  fe/src/store/reducer/type.ts
  fe/src/store/reducer/useGameReducer.tsx
  fe/tsconfig.json
Labels: fe, refactor

#18 [FE] 추가된 메세지 기능 구현
  fe/src/components/GameBoard/CenterArea.tsx
  fe/src/components/GameBoard/Dice.tsx
  fe/src/components/GameBoard/Roulette.tsx
  fe/src/components/Modal/EventModal/EventModal.tsx
  fe/src/components/Player/PlayerCard.tsx
Labels: fe, feat

#19 개인현황판 업데이트 방식 수정[FE]
  fe/src/components/GameBoard/CenterArea.tsx
  fe/src/components/GameBoard/Dice.tsx
  fe/src/components/Player/PlayerCard.tsx
  fe/src/components/Player/PlayerInfo.tsx
  fe/src/components/Player/PlayerStock.tsx
  fe/src/store/reducer/constants.ts
  fe/src/store/reducer/type.ts
  fe/src/store/reducer/useGameReducer.tsx
Labels: fe, refactor

#22 [FE] useHover 커스텀 훅 로직 변경
  fe/src/components/GameBoard/CenterArea.tsx
  fe/src/components/Header/HomeHeader.tsx
  fe/src/components/Player/PlayerStock.tsx
  fe/src/hooks/useHover.ts
  fe/src/store/reducer/constants.ts
Labels: fe, fix

#25 [FE] 황금카드 분리
  fe/src/components/Modal/GoldCardModal/GoldCardModalContent.tsx
  fe/src/components/Modal/GoldCardModal/GoldCardNoTarget.tsx
  fe/src/components/Modal/GoldCardModal/GoldCardPlayer.tsx
  fe/src/components/Modal/GoldCardModal/GoldCardStock.tsx
  fe/src/components/Modal/GoldCardModal/constants.ts
  fe/src/store/reducer/constants.ts
  fe/src/store/reducer/index.ts
  fe/src/store/reducer/type.ts
  fe/src/store/reducer/useGameReducer.tsx
Labels: fe, feat

#30 [FE] 감정표현 기능 구현
  fe/package-lock.json
  fe/package.json
  fe/src/assets/icon/angry.svg
  fe/src/assets/icon/celebrate.svg
  fe/src/assets/icon/clock.svg
  fe/src/assets/icon/cry.svg
  fe/src/assets/icon/emote.svg
  fe/src/assets/icon/hi.svg
  fe/src/assets/icon/laugh.svg
  fe/src/components/GameBoard/EmoteMenu.tsx
  fe/src/components/GameBoard/EmotePanel.tsx
  fe/src/components/GameBoard/constants.ts
  fe/src/components/Player/EmoteBubble.tsx
  fe/src/components/Player/PlayerInfo.tsx
  fe/src/components/icon/icons.ts
  fe/src/pages/GamePage.tsx
  fe/src/store/reducer/constants.ts
  fe/src/store/reducer/index.ts
  fe/src/store/reducer/type.ts
  fe/src/store/reducer/useGameReducer.tsx
  fe/src/styles/designSystem.ts
Labels: fe, feat

#31 [FE] 홈 화면 방 목록 보여주기
  fe/src/api/constants.ts
  fe/src/api/index.ts
  fe/src/api/ws.ts
  fe/src/assets/icon/enter.svg
  fe/src/assets/icon/plus.svg
  fe/src/assets/icon/refresh.svg
  fe/src/components/Footer/HomeFooter.tsx
  fe/src/components/Header/HomeHeader.tsx
  fe/src/components/Home/HomeButtons.tsx
  fe/src/components/Home/HomeGameRoom.tsx
  fe/src/components/Home/HomeGameRooms.tsx
  fe/src/components/Modal/EnterModal/EnterModalContent.tsx
  fe/src/components/icon/icons.ts
  fe/src/pages/HomePage.tsx
  fe/src/pages/SignInPage.tsx
  fe/src/pages/SignUpPage.tsx
  fe/src/store/index.ts
  fe/src/store/type.ts
  fe/src/styles/designSystem.ts
Labels: fe, feat

#33 [FE] 코드 리팩토링
  fe/src/components/GameBoard/Cell.tsx
  fe/src/components/GameBoard/CenterArea.tsx
  fe/src/components/GameBoard/Dice.tsx
  fe/src/components/GameBoard/EmotePanel.tsx
  fe/src/components/GameBoard/constants.ts
  fe/src/components/Modal/GoldCardModal/GoldCardModalContent.tsx
  fe/src/components/Modal/StockBuyModal/StockBuyModal.tsx
  fe/src/components/Modal/StockBuyModal/StockBuyModalContent.tsx
  fe/src/pages/GamePage.tsx
  fe/src/store/reducer/index.ts
  fe/src/store/reducer/type.ts
  fe/src/store/reducer/useGameReducer.tsx
Labels: fe, refactor
