Repository gaemi-marble/gaemi-marble, pull requests merged in 2023-12, with the labels that each got.

#37 [FE] 홈 화면 방 목록 리팩토링
  fe/src/components/GameBoard/EmotePanel.tsx
  fe/src/components/Home/HomeGameRooms.tsx
  fe/src/pages/HomePage.tsx
Labels: fe, refactor

#39 fix: 황금카드칸 버그 임시 수정
  fe/src/store/reducer/useGameReducer.tsx
Labels: bug

#42 [FE] 황금 카드 랜더링 버그 수정
  fe/src/components/Modal/GoldCardModal/GoldCardStock.tsx
  fe/src/pages/GamePage.tsx
  fe/src/store/reducer/useGameReducer.tsx
Labels: fe, fix

#44 [FE] 감옥칸 버그 및 감정표현 관련 오류 수정
  fe/package-lock.json
  fe/package.json
  fe/src/components/GameBoard/Dice.tsx
  fe/src/components/GameBoard/EmotePanel.tsx
  fe/src/components/GameBoard/constants.ts
  fe/src/components/Player/PlayerInfo.tsx
  fe/src/components/Player/constants.ts
Labels: fe, fix

#46 [BE] 보유 주식가치 계산 수정
  be/src/main/java/codesquad/gaemimarble/game/player/entity/Player.java
  be/src/main/java/codesquad/gaemimarble/game/player/service/PlayerService.java
Labels: be, fix

#47 [FE] 게임 페이지 전반적인 UI 수정
  fe/index.html
  fe/src/components/GameBoard/Cell.tsx
  fe/src/components/GameBoard/CenterArea.tsx
  fe/src/components/GameBoard/EmotePanel.tsx
  fe/src/components/GameBoard/GameBoard.tsx
  fe/src/components/GameBoard/PlayerToken.tsx
  fe/src/components/GameBoard/Roulette.tsx
  fe/src/components/Header/HomeHeader.tsx
  fe/src/components/Home/HomeGameRoom.tsx
  fe/src/components/Player/EmoteBubble.tsx
  fe/src/components/Player/LeftPlayers.tsx
  fe/src/components/Player/PlayerCard.tsx
  fe/src/components/Player/PlayerInfo.tsx
  fe/src/components/Player/RightPlayers.tsx
  fe/src/pages/GamePage.tsx
  fe/src/pages/SignInPage.tsx
  fe/src/pages/SignUpPage.tsx
  fe/src/store/reducer/constants.ts
  fe/src/store/reducer/type.ts
  fe/src/styles/GlobalStyle.ts
  fe/src/styles/designSystem.ts
Labels: fe, refactor, ui

#51 [FE] 홈 페이지 페이지네이션 기능 추가 및 디자인 업그레이드
  fe/src/components/Footer/HomeFooter.tsx
  fe/src/components/Header/HomeHeader.tsx
  fe/src/components/Home/HomeButtons.tsx
  fe/src/components/Home/HomeGameRoom.tsx
  fe/src/components/Home/HomeGameRooms.tsx
  fe/src/components/Home/HomeGameRoomsPage.tsx
  fe/src/components/Home/HomeMain.tsx
  fe/src/components/Home/constants.ts
  fe/src/pages/HomePage.tsx
  fe/src/store/reducer/constants.ts
  fe/src/store/reducer/index.ts
Labels: fe, feat, ui

#53 [FE] 순간이동 Cell 클릭 버그 해결
  fe/src/components/GameBoard/Cell.tsx
  fe/src/components/GameBoard/CenterArea.tsx
  fe/src/components/GameBoard/Roulette.tsx
Labels: fe, fix

#59 [FE] 플레이어 카드 요소 배치 수정 및 감정 표현 말풍선 짤림 버그 수정
  fe/src/components/Player/EmoteBubble.tsx
  fe/src/components/Player/PlayerCard.tsx
  fe/src/components/Player/PlayerStock.tsx
  fe/src/components/Player/PlayerStockList.tsx
  fe/src/components/Player/constants.ts
Labels: fe, refactor, ui
